### ISSUE TITLE
jobs are not saved

### ISSUE THREAD

**Issue by emmanuelmathot** [jbox-web/redmine_jenkins#8] opened 2014-08-26 15:33 UTC
In the "Add a job" popup with the "job Name" and "repository", when I click "Save", nothing happens.

**Comment by luismaia** [comment] 2014-09-03 11:03
I have exactly the same problem.
After debugging, at least in my case, this was caused by the following error:

ActiveRecord::StatementInvalid (Mysql2::Error: Column 'comment' cannot be null: INSERT INTO `jenkins_build_changesets` (`comment`, `jenkins_build_id`, `repository_id`, `revision`) VALUES (NULL, 28, 5, '14604'))

In my case the Jenkins server sends no information about the comment.

**Comment by n-rodriguez** [comment] 2014-09-08 21:50
Fixed by PR https://github.com/jbox-web/redmine_jenkins/pull/11

**Closed as completed by n-rodriguez** 2014-09-08 21:50 UTC
Labels: bug
